env:
  browser: true
  es2020: true
  node: true
extends:
  - plugin:coffee/eslint-recommended
  - plugin:coffee/import
  - plugin:import/recommended
  - plugin:meteor/recommended
  - plugin:coffee/react-recommended
  - plugin:coffee/disable-incompatible
globals:
  Meteor: readonly
  WebApp: readonly
ignorePatterns:
  - .meteor
parser: eslint-plugin-coffee
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - coffee
  - import
  - meteor
  - react
rules:
  linebreak-style:
    - error
    - unix
  coffee/jsx-no-target-blank:
    - error
    - allowReferrer: true
  coffee/no-inner-declarations: off
  coffee/no-unused-vars:
    - error
    - args: none  # allow callbacks of the form (e) -> ...not using e...
  coffee/no-useless-escape: off
  import/default: off
  import/no-named-as-default-member: off
  react/no-unescaped-entities:
    - warn
    - forbid: ['>', '"', '}']
  react/prop-types: off
  meteor/no-session: off
  meteor/audit-argument-checks:
    - error
    - checkEquivalents:
      - checkId
      - checkMeeting
settings:
  import/ignore:
    - node_modules
  import/resolver:
    meteor:
      extensions:
        - .coffee
        - .js
        - .ts
  react:
    version: detect
